### PR TITLE
Small code adjustment to resolve incompatibility with yum cookbook v3.x.

### PR DESCRIPTION
**Pull request by fabiendelpierre**
I posted [an issue](https://github.com/wharton/chef-shibboleth-sp/issues/8) earlier but decided to just fork the repo and fix the code that I thought was the problem. This is the first time I do anything like this so please let me know if I messed up somehow!

### CODE REVIEW

**Comment by nmische** [comment]
Thanks for this. This was something I've been meaning to address but just haven't had the time. I will try to test in the next week or so and let you know how I make out.

**Comment by bflad** [comment]
This LGTM. Only other adjustments I would make are releasing this as 0.3.0 and splitting out the depends in the metadata so we can properly list `depends 'yum', '> 3.0'`

**Comment by fabiendelpierre** [comment]
@bflad  That makes sense -- now bear with me here if I'm asking a silly question since I'm a complete newbie: is this something I would be expected to provide under standard GitHub M.O./etiquette? I'm happy to do it, just I'm not sure what the expectation is! I'm also not sure how to edit the content of this pull request with the adjustments you suggested (looks like it's not actually possible but I don't know).

**Comment by bflad** [comment]
You're doing just fine! You're more than welcome to change it then just leave a comment that you did (Github won't notify us via email if you change your PR). Changing the PR is easy actually. Since you're working off your master branch, all you need to do is create a commit with the new change and push to master (defualt branch) on your repository. The PR will be automatically updated.

In the future, you may want to create a new branch on your repository before trying to create a pull request, but that doesn't affect our side in any way. It would just so you could always have a clean fork of our repository on the master branch in case your PR was never merged (for whatever reason) or if you wanted to make separate changes. If you'd like to know how to work like that you can definitely contact me outside of here (my email is all over my repositories).

Hope this helps!

**Comment by fabiendelpierre** [comment]
Done! And thanks for the suggestions!

**Comment by bflad** [comment]
@nmische LGTM

**Pull request merged**
