### PR TITLE
Added logging root attribute and shibd.logger template

### PR DESCRIPTION
**Pull request by bflad**
Please let me know if you have any questions/concerns.

### CODE REVIEW

**Comment by nmische** [comment]
Good start, but I I'd like to see support for tracing of SAML messages. Don't let that hold up this PR though.

**Comment by bflad** [comment]
How about all dem attributes?

**Comment by nmische** [comment]
What if we only add the line to the config if one of those additional attributes is defined?

**Comment by bflad** [comment]
They're originally part of the configuration commented out, but set as INFO because root is INFO by default. I'm flexible with the implementation, but it would make for a harder to read template file if we're just controlling the # in front of the configuration line for when its set to DEBUG.

**Comment by nmische** [comment]
Yeah, I just realized after looking at 213bd81 that it would be nice to still be able to quickly set everything to DEBUG with the root logging level. It may not be worth the complexity though.

**Comment by bflad** [comment]
We could change node['shibboleth-sp']['logging'] to just uncomment all of those additional lines. One quick and dirty change for a bunch more logging.

**Comment by nmische** [comment]
@bflad Not sure if you care about this anymore, but this is what I think I'm going to do here.

**Comment by bflad** [comment]
fine by me.

**Pull request merged**
